feat: Add ingress counter to avoid undesired deletion, Use networking…
dbsystel/AmazonRoute53-ingress-controller pull request #3
Opened 2020-02-24 15:45 UTC by Kirchen99

feat: Add ingress counter to avoid undesired deletion, Use networking api instead of extentions for ingress, Add CNAME support, Recordset type configurable with parameter (by external expert on behalf of DB Systel GmbH)

2020-02-24 15:57 UTC, dbluxo requested changes

2020-02-24 15:57 UTC, dbluxo commented on cmd/main.go
> +	"github.com/Kirchen99/AmazonRoute53-ingress-controller/controller"
we have to use github.com/dbsystel....

2020-02-24 15:57 UTC, dbluxo commented on controller/controller.go
> +	"github.com/Kirchen99/AmazonRoute53-ingress-controller/aws"
we have to use github.com/dbsystel....

2020-02-24 15:57 UTC, dbluxo commented on go.mod
> -module github.com/dbsystel/AmazonRoute53-ingress-controller
we have to use github.com/dbsystel....

2020-02-24 16:12 UTC, Kirchen99 commented on cmd/main.go
> +	"github.com/Kirchen99/AmazonRoute53-ingress-controller/controller"
Yep

2020-02-24 16:12 UTC, Kirchen99 commented on controller/controller.go
> +	"github.com/Kirchen99/AmazonRoute53-ingress-controller/aws"
OK

2020-02-24 16:12 UTC, Kirchen99 commented on go.mod
> -module github.com/dbsystel/AmazonRoute53-ingress-controller
good point

2020-02-24 16:15 UTC, dbluxo requested changes

2020-02-24 16:15 UTC, dbluxo commented on go.mod
> +module github.com/Kirchen99/AmazonRoute53-ingress-controller
we have to use github.com/dbsystel....

2020-03-10 10:27 UTC, dbluxo approved these changes

2020-03-10 10:29 UTC, merged